name: Machinery
version: 2.0
main: me.oriharel.machinery.Machinery
api-version: 1.13
load: POSTWORLD
authors: [Heknon]
depend:
  - Kotlin
description: Adds machines. Factorio in Minecraft
website: https://oriharel.me
